<?php
/**
 * GetletterTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Postbode.nu
 *
 * Postbode.nu API for sending letters   # Getting started  ## Authentication  To make use of the API one needs a account and an API-Key  Account: https://app.postbode.nu/register<br/> API Key: https://app.postbode.nu/settings/api -> \"API Key Aanmaken\"  Use API key in header: > X-Authorization: XXXXXXXXX-YOUR-API-KEY-XXXXXXXXX   ## Sandbox mode  For testing purposes there is a sandbox mode.   To activate: https://app.postbode.nu/mailbox/settings -> Testomgeving  While active no letters will be send in production. After disabling only new letters will be printed and send to reciever.   ## Billing  Payement by letter and upfront via you mailbox balance.  To deposit credit: Login app.postbode.nu -> Tegoed -> Tegoed aanvullen  For seamless experience activate auto deposit. Please reach out to us on postkantoor@postbode.nu for activation.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GetletterTest Class Doc Comment
 *
 * @category    Class */
// * @description Getletter
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetletterTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Getletter"
     */
    public function testGetletter()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "mailbox_id"
     */
    public function testPropertyMailboxId()
    {

    }

    /**
     * Test attribute "envelope_id"
     */
    public function testPropertyEnvelopeId()
    {

    }

    /**
     * Test attribute "shipping_method_id"
     */
    public function testPropertyShippingMethodId()
    {

    }

    /**
     * Test attribute "service"
     */
    public function testPropertyService()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "color"
     */
    public function testPropertyColor()
    {

    }

    /**
     * Test attribute "printing"
     */
    public function testPropertyPrinting()
    {

    }

    /**
     * Test attribute "paper_weight"
     */
    public function testPropertyPaperWeight()
    {

    }

    /**
     * Test attribute "paper_size"
     */
    public function testPropertyPaperSize()
    {

    }

    /**
     * Test attribute "tracking_code"
     */
    public function testPropertyTrackingCode()
    {

    }

    /**
     * Test attribute "formatted_id"
     */
    public function testPropertyFormattedId()
    {

    }

    /**
     * Test attribute "shipping_id"
     */
    public function testPropertyShippingId()
    {

    }

    /**
     * Test attribute "weight"
     */
    public function testPropertyWeight()
    {

    }

    /**
     * Test attribute "pages"
     */
    public function testPropertyPages()
    {

    }

    /**
     * Test attribute "sheets"
     */
    public function testPropertySheets()
    {

    }

}
